# Generated by Django 2.0 on 2018-03-06 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_auto_20170826_1201'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='goodscategorybrand',
            table='goods_goodsbrand',
        ),
    ]
